import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'k2',
    name: 'Designer Kids Ethnic Wear',
    price: 1499,
    originalPrice: 2499,
    description: 'Beautifully crafted designer ethnic wear for kids. Made with soft, skin-friendly fabric for maximum comfort during celebrations.',
    category: 'Kids',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775226009/LS_kids_wear_google_img_4_hisib2.jpg'],
    sizes: ['2Y', '4Y', '6Y', '8Y'],
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviews: 12
  },
  {
    id: 'k3',
    name: 'Premium Festive Kids Set',
    price: 1899,
    originalPrice: 2999,
    description: 'A premium festive set for children, featuring elegant patterns and vibrant colors. Perfect for weddings and festivals.',
    category: 'Kids',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775226005/LS_kids_wear_google_img_3_v4inhw.webp'],
    sizes: ['4Y', '6Y', '8Y', '10Y'],
    isFeatured: true,
    rating: 4.8,
    reviews: 15
  },
  {
    id: 'k4',
    name: 'Traditional Kids Kurta Pajama',
    price: 1299,
    originalPrice: 1999,
    description: 'Classic traditional kurta pajama set for boys. Lightweight and breathable fabric ensures all-day comfort.',
    category: 'Kids',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775225991/LS_kids_wear_google_img_2_tqcxxz.webp'],
    sizes: ['2Y', '4Y', '6Y', '8Y'],
    isFeatured: true,
    isNew: true,
    rating: 4.7,
    reviews: 10
  },
  {
    id: 'k5',
    name: 'Elegant Kids Celebration Wear',
    price: 2199,
    originalPrice: 3499,
    description: 'Exquisite celebration wear for kids with intricate detailing. A sophisticated choice for special family events.',
    category: 'Kids',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775225984/LS_kids_wear_Google_img_q92jy9.jpg'],
    sizes: ['6Y', '8Y', '10Y', '12Y'],
    isFeatured: true,
    rating: 5.0,
    reviews: 8
  },
  {
    id: 'w3',
    name: 'Premium Silk Saree Collection',
    price: 4999,
    originalPrice: 6999,
    description: 'Exquisite silk saree with intricate gold zari work. A perfect blend of tradition and modern elegance for special occasions.',
    category: 'Women',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775224499/LS_women_model1_lchtwu.jpg'],
    sizes: ['Free Size'],
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviews: 18
  },
  {
    id: 'w4',
    name: 'Designer Embroidered Kurta Set',
    price: 3299,
    originalPrice: 4500,
    description: 'Hand-embroidered designer kurta set in soft pastel shades. Features delicate thread work and a matching dupatta.',
    category: 'Women',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775224476/LS_women_model2_xysfeo.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    isFeatured: true,
    rating: 4.8,
    reviews: 22
  },
  {
    id: 'w5',
    name: 'Contemporary Ethnic Gown',
    price: 5499,
    originalPrice: 7999,
    description: 'Stunning floor-length ethnic gown with modern silhouettes. Crafted from premium georgette with subtle sequin detailing.',
    category: 'Women',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775224462/LS_lady_model3_fpcxw6.jpg'],
    sizes: ['M', 'L', 'XL'],
    isFeatured: true,
    isNew: true,
    rating: 5.0,
    reviews: 15
  },
  {
    id: 'm3',
    name: 'Premium Silk Kurta for Men',
    price: 2499,
    originalPrice: 3999,
    description: 'Elegant silk kurta with subtle embroidery on the collar and cuffs. Perfect for festive occasions and weddings.',
    category: 'Men',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775224862/LS_men_model_1_r6bf19.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviews: 14
  },
  {
    id: 'm4',
    name: 'Designer Ethnic Jacket Set',
    price: 4299,
    originalPrice: 5999,
    description: 'A sophisticated three-piece ethnic set featuring a designer Nehru jacket over a premium cotton kurta.',
    category: 'Men',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775224871/LS_men_model_2_i8k38j.webp'],
    sizes: ['S', 'M', 'L', 'XL'],
    isFeatured: true,
    rating: 4.8,
    reviews: 20
  },
  {
    id: 'm5',
    name: 'Traditional Wedding Sherwani',
    price: 8999,
    originalPrice: 12999,
    description: 'Exquisite wedding sherwani with heavy hand-embroidery and premium fabric. Designed for the modern groom.',
    category: 'Men',
    images: ['https://res.cloudinary.com/duy2rot8s/image/upload/v1775224884/LS_men_model_3_k3oxov.webp'],
    sizes: ['M', 'L', 'XL'],
    isFeatured: true,
    isNew: true,
    rating: 5.0,
    reviews: 12
  },
  {
    id: 'm6',
    name: 'Premium Formal Shirt',
    price: 1299,
    originalPrice: 1999,
    description: 'A high-quality formal shirt designed for a sharp, professional look. Crafted from premium breathable cotton, this shirt offers both comfort and style for your office and formal events.',
    category: 'Men',
    images: [
      'https://res.cloudinary.com/duy2rot8s/image/upload/v1775569701/demo_img_su8yfp.webp',
      'https://res.cloudinary.com/duy2rot8s/image/upload/v1775569745/demo_img_2_m89fir.webp',
      'https://res.cloudinary.com/duy2rot8s/image/upload/v1775569757/demo_img_3_wozmtw.jpg',
      'https://res.cloudinary.com/duy2rot8s/image/upload/v1775569769/demo_img_4_kyiqrz.jpg'
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isFeatured: true,
    isNew: true,
    rating: 4.8,
    reviews: 15
  }
];
